apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  annotations:
    policy.open-cluster-management.io/categories: PR.IP Information Protection Processes and Procedures
    policy.open-cluster-management.io/controls: PR.IP-1 Baseline Configuration
    policy.open-cluster-management.io/standards: NIST-CSF
  name: sushi-quotas
  namespace: rhacm-policies
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: limite-ranges-container-limit-range
        spec:
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - sushi*
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: LimitRange
                metadata:
                  name: container-limit-range
                spec:
                  limits:
                    - default:
                        cpu: 500m
                        memory: 512Mi
                      defaultRequest:
                        cpu: 50m
                        memory: 256Mi
                      type: Container
          remediationAction: inform
          severity: medium
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: default-quotas
        spec:
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - sushi*
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: ResourceQuota
                metadata:
                  name: resource-quotas
                spec:
                  hard:
                    pods: '4'
                    requests.cpu: '1'
                    requests.memory: 1Gi
                    requests.storage: 2Gi
                    limits.cpu: '2'
                    limits.memory: 2Gi
          remediationAction: inform
          severity: medium
  remediationAction: enforce