apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: sushi-dev-placement
  namespace: sushiweb
spec:
  # clusters:
  #   - name: ruby
  clusterSelector:
    matchLabels:
      sushi: 'true'
      env: 'dev'
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: sushi-prod-placement
  namespace: sushiweb
spec:
  # clusters:
  #   - name: ruby
  clusterSelector:
    matchLabels:
      sushi: 'true'
      env: 'prod'
