apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  annotations:
    apps.open-cluster-management.io/reconcile-rate: high
  name: gitops-demo
  namespace: rhacm-policies
spec:
  type: Git
  pathname: https://github.com/ibm-garage-mop/gitops-demo.git