apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: policies-placement
  namespace: rhacm-policies
spec:
  clusterConditions:
    - status: 'True'
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchLabels:
      local-cluster: 'true'
    # matchExpressions:
    #   - key: name
    #     operator: In
    #     values: 
    #       - 'local-cluster'