apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: seb
    apps.open-cluster-management.io/git-path: policies/sushi
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: policy-sushi
  name: policy-sushi
  namespace: rhacm-policy
spec:
  channel: rhacm-policies/policy-sushi
  placement:
    placementRef:
      kind: PlacementRule
      name: sushi-placement