apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: dev
    apps.open-cluster-management.io/git-path: policies/sushi
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: sushi-policies
  name: sushi-policies
  namespace: rhacm-policies
spec:
  channel: rhacm-policies/gitops-demo
  placement:
    placementRef:
      kind: PlacementRule
      name: policies-placement