apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-sushi-policies
  namespace: rhacm-policies
spec:
  clusterConditions:
    - status: 'True'
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: name
        operator: In
        values: 
          - 'local-cluster'