apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: sushi-policy-generator
placementBindingDefaults:
  name: sushi-placement-binding
policyDefaults:
  namespace: rhacm-policies
  placement:
    name: sushi-placement-rule
    clusterSelectors:
      matchExpressions:
        - key: sushi
          operator: In
          values: 
            - 'true'
  remediationAction: enforce
  severity: medium
policies:
  - name: sushi-policy-networkpolicies
    consolidateManifests: false
    manifests:
      - path: sushi-networkpolicies.yaml
  # - name: sushi-policy-quotas
  #   manifests:
  #     - path: sushi-quotas.yaml