apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: sushi-network-policies
placementBindingDefaults:
  name: binding-sushi-netpolicies
policyDefaults:
  namespaceSelector:
    exclude: [kube-*, sushiweb-pipeline]
    include: [sushi]
  placement:
    name: sushi-placement
    clusterSelectors:
      sushi: 'true'
  remediationAction: enforce
policies:
  - name: allow-same-namespace.yaml
    manifests:
      - path: netpolicy-deny-other-ns.yaml
