apiVersion: v1
kind: LimitRange
metadata:
  name: default-limit-range
spec:
  limits:
    - default:
        memory: 512Gi
        cpu: 500m
      defaultRequest:
        memory: 256Mi
        cpu: 50m
      type: Container