apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quotas
spec:
  hard:
    pods: '2'
    requests.cpu: '1'
    requests.memory: 1Gi
    requests.storage: 2Gi
    limits.cpu: '2'
    limits.memory: 2Gi