---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: sushiweb
  name: sushi-placement
  namespace: sushiweb-rhacm
spec:
  # clusters:
  #   - name: ruby
  clusterSelector:
    matchLabels:
      sushi: 'true'
    # matchExpressions:
    #   - key: sushi
    #     operator: In
    #     values: 
    #       - 'true'
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
  # clusterReplicas: 1  #Apply to how many matched clusters, default is ALL
