---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: sushiweb
  labels:
    app: sushiweb
  namespace: sushiweb-rhacm
  annotations:
    apps.open-cluster-management.io/github-path: apps/sushiweb/base
    apps.open-cluster-management.io/github-branch: seb
    apps.open-cluster-management.io/reconcile-option: merge
    apps.open-cluster-management.io/reconcile-rate: high
spec:
  channel: sushiweb-rhacm/sushiweb
  placement:
    placementRef:
      kind: PlacementRule
      name: sushi-placement
