apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-sushiweb
  namespace: rhacm-policies
spec:
  clusterConditions:
    - status: 'True'
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: sushi
        operator: In
        values: 
          - 'true'