apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: sushi-placement
  namespace: sushi-prod
spec:
  # clusters:
  #   - name: ruby
  clusterSelector:
    matchLabels:
      sushi: 'true'
      env: 'prod'
